name: Update data.json

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (UTC)
  workflow_dispatch:        # allows manual run from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingest_gscholar
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: |
          python ingest_gscholar.py \
            --id sJB6rcgAAAAJ \
            --max 400 \
            --pages both \
            --crossref \
            --arxiv-lookup \
            --out data.json

      - name: Commit updated data.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json
          git diff --quiet && echo "No changes to commit" || git commit -m "Update data.json [skip ci]"
          git push
